### ISSUE TITLE
Package does not work as recomended in the Readme file

### ISSUE THREAD

**Issue by PauloBarbeiro** [rajasegar/ember-react-fc#1]
While following the configuration suggested in the README file, I ran into problems when executing the application.
For simple debugging I start new Ember applications with the HelloWorld component. The generator command does work and outputs the expected .jsx file. The problem appears while running the app.

I try with broccoli and embroider. With Embroider the error shows at the build time, and with broccoli the error shows on browser.

Environment:
- Platform Mac SIlicon
- Node 22.11.0 
- NPM 10.9.0
- Ember CLI 5.12.0

## Broccoli error

1. Create app and setup
```shell
ember new fc-simple
cd fc-simple
ember install ember-react-fc
ember g react-component hello-world
```

2. Add hello-word component in templates/application.hbs
```handlebars
{{page-title "FcSimple"}}

{{outlet}}

<HelloWord />
```

3. Setup ember-cli-build.js
```javascript
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function (defaults) {
  const app = new EmberApp(defaults, {
    // Add options here
    'ember-react-fc': {
      outputFile: '/assets/react.js',
    },
  });

  return app.toTree();
};
```

4. Run application
```shell
npm run start
```

all good in the console output
```shell
> fc-simple@0.0.0 start
> ember serve


Build successful (2216ms) – Serving on http://localhost:4200/

Slowest Nodes (totalTime >= 5%)                    | Total (avg) 
---------------------------------------------------+-------------
ember-auto-import-webpack (1)                      | 1414ms      
Babel: @ember/test-helpers (1) 
```

Error in browser:

`ember.js:6712 

Error occurred:

- While rendering:
  -top-level
    application

execute @ ember.js:6712
(anonymous) @ ember.js:6713
debug$1.runInTrackingTransaction @ ember.js:1360
sync @ ember.js:6713
(anonymous) @ ember.js:14366
(anonymous) @ ember.js:14363
(anonymous) @ ember.js:14398
inTransaction @ ember.js:6494
_renderRoots @ ember.js:14391
_renderRootsTransaction @ ember.js:14403
_renderRoot @ ember.js:14391
_appendDefinition @ ember.js:14388
appendOutletView @ ember.js:14388
invoke @ ember.js:3200
flush @ ember.js:3195
flush @ ember.js:3214
_end @ ember.js:3244
end @ ember.js:3224
_run @ ember.js:3244
run @ ember.js:3224
run$1 @ ember.js:3307
callback @ ember.js:15731
ember.js:1531 Uncaught Error: Attempted to resolve `hello-word`, which was expected to be a component, but nothing was found.
    at ember.js:1531:1
    at encodeOp (ember.js:1534:1)
    at pushOp (ember.js:1782:1)
    at ember.js:1776:1
    at Compilers.compile (ember.js:1570:1)
    at compileStatements (ember.js:1782:1)
    at ember.js:1782:1
    at CompilableTemplateImpl.compile (ember.js:1782:1)
    at Object.evaluate (ember.js:6385:1)
    at Object.evaluate (ember.js:6350:1)
(anonymous) @ ember.js:1531
encodeOp @ ember.js:1534
pushOp @ ember.js:1782
(anonymous) @ ember.js:1776
compile @ ember.js:1570
compileStatements @ ember.js:1782
(anonymous) @ ember.js:1782
compile @ ember.js:1782
(anonymous) @ ember.js:6385
evaluate @ ember.js:6350
evaluateSyscall @ ember.js:6665
evaluateInner @ ember.js:6665
evaluateOuter @ ember.js:6665
next @ ember.js:6712
_execute @ ember.js:6712
execute @ ember.js:6707
(anonymous) @ ember.js:6713
debug$1.runInTrackingTransaction @ ember.js:1360
sync @ ember.js:6713
(anonymous) @ ember.js:14366
(anonymous) @ ember.js:14363
(anonymous) @ ember.js:14398
inTransaction @ ember.js:6494
_renderRoots @ ember.js:14391
_renderRootsTransaction @ ember.js:14403
_renderRoot @ ember.js:14391
_appendDefinition @ ember.js:14388
appendOutletView @ ember.js:14388
invoke @ ember.js:3200
flush @ ember.js:3195
flush @ ember.js:3214
_end @ ember.js:3244
end @ ember.js:3224
_run @ ember.js:3244
run @ ember.js:3224
run$1 @ ember.js:3307
callback @ ember.js:15731
`

## Embroider error

1. Create app and setup
```shell
ember new fc-embroider --embroider
cd fc-embroider
ember install ember-react-fc
ember g react-component hello-world
```

2. Add hello-word component in templates/application.hbs
```handlebars
{{page-title "FcEmbroider"}}

{{outlet}}

{{! The following component displays Ember's default welcome message. }}
<HelloWord />
{{! Feel free to remove this! }}
```

3. Setup ember-cli-build.js
```javascript
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function (defaults) {
  const app = new EmberApp(defaults, {
    // Add options here
    'ember-react-fc': {
      outputFile: '/assets/react.js',
    },
  });

  const { Webpack } = require('@embroider/webpack');
  return require('@embroider/compat').compatBuild(app, Webpack, {
    staticAddonTestSupportTrees: true,
    staticAddonTrees: true,
    staticHelpers: true,
    staticModifiers: true,
    staticComponents: true,
    staticEmberSource: true,
    skipBabel: [
      {
        package: 'qunit',
      },
    ],
  });
};
```

4. Run application
```shell
npm run start
```

Error in the console output
```shell
npm run start

> fc-embroider@0.0.0 start
> ember serve

⠏ building... [Babel: ember-source > applyPatches][BABEL] Note: The code generator has deoptimised the styling of /Users/me/Documents/apps/fc-embroider/ember/ember-template-compiler.js as it exceeds the max of 500KB.
⠹ building... [Babel: ember-source > applyPatches][BABEL] Note: The code generator has deoptimised the styling of /Users/me/Documents/apps/fc-embroider/ember/ember.js as it exceeds the max of 500KB.
⠋ building... [@embroider/webpack]assets by chunk 3.78 MiB (id hint: vendors)
  asset assets/chunk.55af6d3e7277cb7f338d.js 3.02 MiB [emitted] [immutable] [big] (id hint: vendors)
  asset assets/chunk.157251762ca1ca1783f9.js 777 KiB [emitted] [immutable] [big] (id hint: vendors)
asset assets/chunk.f5d45adb2c32ede01f59.js 586 KiB [emitted] [immutable] [big] (name: assets/test.js)
asset assets/chunk.9f0974a7ad44a04f86f8.js 298 KiB [emitted] [immutable] [big] (name: assets/fc-embroider.js)
Entrypoint assets/fc-embroider.js [big] 3.31 MiB = assets/chunk.55af6d3e7277cb7f338d.js 3.02 MiB assets/chunk.9f0974a7ad44a04f86f8.js 298 KiB
Entrypoint assets/test.js [big] 4.35 MiB = assets/chunk.55af6d3e7277cb7f338d.js 3.02 MiB assets/chunk.157251762ca1ca1783f9.js 777 KiB assets/chunk.f5d45adb2c32ede01f59.js 586 KiB
runtime modules 6.8 KiB 14 modules
modules by path ../ 2.75 MiB
  modules by path ../rewritten-packages/ 1.7 MiB 249 modules
  modules by path ../../ 1.05 MiB 59 modules
modules by path ./ 6.76 KiB
  modules by path ./assets/*.js 2.8 KiB 2 modules
  modules by path ./tests/ 1.55 KiB 2 modules
  modules by path ./*.js 1.13 KiB 2 modules
  ./config/environment.js 554 bytes [built] [code generated]
  ./templates/application.hbs 758 bytes [built] [code generated]
+ 118 modules

ERROR in ./templates/application.hbs 2:0-65
Module not found: Error: Can't resolve '#embroider_compat/components/hello-word' in '/Users/me/Documents/apps/fc-embroider'
resolve '#embroider_compat/components/hello-word' in '/Users/me/Documents/apps/fc-embroider'
  using description file: /Users/me/Documents/apps/fc-embroider/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
 @ ./assets/fc-embroider.js 49:13-62

webpack 5.96.1 compiled with 1 error in 3091 ms
Build Error (PackagerRunner) in templates/application.hbs

Module not found: Error: Can't resolve '#embroider_compat/components/hello-word' in '/Users/me/Documents/apps/fc-embroider'


Stack Trace and Error Report: /var/folders/t6/44719hdn64zc01z5rqh4rh_80000gn/T/error.dump.97d7590afbfbea4359ea2bf1b8783779.log
```

**Comment by ascudder** [comment]
I'm also experiencing this issue with Ember 3.28. Anyone have ideas on how to solve this?

**Comment by NullVoxPopuli** [comment]
do you need ember-react-fc? 🤔 

Here is React in the [Ember REPL](https://limber.glimdown.com/edit?c=JYWwDg9gTgLgBAbziCATYAzYBTKcC%2BcGUEIcA5NiAEa4C0K6Wu5A3AFDsYCuAdgMYxgEXnABK2AIaCAgmDAAKAJSJ2cOAHoNcAJJwAFpIBu2OACsAzgA846C5OoAbbKjjBRMfcAviAogAUAGTgFT283H0k4AHEAKQBlImBnJTU4KGwYbihRCWkYADp%2BDMkYbF9nEGxeGAUAInQjOoAaOF5uR0dWuoAJbE6IVrzBAEI6pQ58NXYtOAAVLx9wqIB3aABrOkkSPldafkluC1M9VBFyeEMTdKlBDRLBOjOQGe13CxhJTpc3D0W-IKtFamXjYH4wCBwFaSYDwDDQOCeUwWYrAMAwHwQuCOCCSVDsfgiD62CCBUq4OAAXhCGF4KkpAD44McYHNQNgINxarTWgBGAAMgomnEJvGJDxgYggEHg1MYmBwUAU-So1VlTIQaTOZLKSuUVI1aXUwxgABEAPIAWSKJTKUplysqaqUBQyvFQuAUJrkiiUEzgaXwqSDHHYAB4yuBHOSGWkwyioGj4MUIBYLNBgABzdzMqD8Sl1fQwGBgCwALi0fDA60zRVI91uMAAAryABwabggVAN-IFD0mHFgKo1AqWOoMsMaBNJ2PqeOo9FwFNpjPZ0QWPMFosl8uV3jV2uEkA9x7PFvtzvdiVPUh97ADiBDtWjizjyfT9GzgNzxqIBAS%2B0YHwfAJw0RpY0nSMwGjMpY3YIA&format=gjs) i have.

In a real app, all that's needed:
- ember-auto-import
- enable jsx transforming

The thing I'm not sure about:
- what does `WithEmberSupport` do? is it a wrapper for the modifier?

If I were to add React to an Ember app as "Islands", I'd do it this way:

```gjs
import ReactA from './components/.....';
import ReactB from './components/....';
import { renderReact } from './somewhere';

<template>
  <div {{renderReact ReactA}}></div>
  <div {{renderReact ReactB}}></div>
</template>
```
